#!/usr/bin/env ansible-playbook
---
- name: mcabber config
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      sudo: yes
      when: no_sudo is not defined
      with_items:
        - mcabber
        - pass
